# Generated by Django 5.2 on 2025-04-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplydeliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplydeliverreference',
            name='supply_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_delivery_reference_contract', to='supplydeliveries.supplydelivery'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_delivery_destination', to='supplydeliveries.supplydeliverydestinationreference'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='part_of',
            field=models.ManyToManyField(blank=True, related_name='supply_delivery_part_of', to='supplydeliveries.supplydeliverycontractreference'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='receiver',
            field=models.ManyToManyField(blank=True, related_name='supply_delivery_receiver', to='supplydeliveries.supplydeliveryreceiverreference'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='supplied_item',
            field=models.ManyToManyField(blank=True, related_name='supply_delivery_supplied_item', to='supplydeliveries.supplydeliverysupplieditem'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_delivery_supplier', to='supplydeliveries.supplydeliverysupplierreference'),
        ),
        migrations.AlterField(
            model_name='supplydeliverycontractreference',
            name='supply_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_delivery_contracts_supply_delivery', to='supplydeliveries.supplydelivery'),
        ),
        migrations.AlterField(
            model_name='supplydeliverysupplieditem',
            name='item_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_delivery_supplied_item_item_reference', to='supplydeliveries.supplydeliverysupplieditemitemreference'),
        ),
    ]
