# Generated by Django 5.2 on 2025-04-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagingstudies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingstudy',
            name='based_on',
            field=models.ManyToManyField(blank=True, related_name='imaging_study_based_on', to='imagingstudies.imagingstudybasedonreference'),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='procedure',
            field=models.ManyToManyField(blank=True, related_name='imaging_study_procedure', to='imagingstudies.imagingstudyprocedurereference'),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='reason',
            field=models.ManyToManyField(blank=True, related_name='imaging_study_reason', to='imagingstudies.imagingstudyreasonreference'),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='imaging_study_series', to='imagingstudies.imagingstudyseries'),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imaging_study_subject', to='imagingstudies.imagingstudysubjectreference'),
        ),
        migrations.AlterField(
            model_name='imagingstudyreference',
            name='imaging_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imaging_study_reference_imaging_study', to='imagingstudies.imagingstudy'),
        ),
        migrations.AlterField(
            model_name='imagingstudyseries',
            name='instance',
            field=models.ManyToManyField(blank=True, related_name='imaging_study_series_instance', to='imagingstudies.imagingstudyseriesinstance'),
        ),
        migrations.AlterField(
            model_name='imagingstudyseries',
            name='performer',
            field=models.ManyToManyField(blank=True, related_name='imaging_study_series_performer', to='imagingstudies.imagingstudyseriesperformer'),
        ),
        migrations.AlterField(
            model_name='imagingstudyseriesperformer',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imaging_study_series_performer_reference', to='imagingstudies.imagingstudyseriesperformeractorreference'),
        ),
    ]
