# Generated by Django 5.2 on 2025-04-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodeofcares', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeofcare',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, related_name='episode_of_care_diagnosis', to='episodeofcares.episodeofcarediagnosis'),
        ),
        migrations.AlterField(
            model_name='episodeofcarereason',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_of_care_reason_value', to='episodeofcares.episodeofcarereasonvaluecodeablereference'),
        ),
    ]
