# Generated by Django 5.2 on 2025-04-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomicstudies', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomicstudy',
            name='analysis',
            field=models.ManyToManyField(blank=True, related_name='genomic_study_analysis', to='genomicstudies.genomicstudyanalysis'),
        ),
        migrations.AlterField(
            model_name='genomicstudy',
            name='based_on',
            field=models.ManyToManyField(blank=True, related_name='genomic_study_based_on', to='genomicstudies.genomicstudybasedonreference'),
        ),
        migrations.AlterField(
            model_name='genomicstudy',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='genomic_study_subject', to='genomicstudies.genomicstudysubjectreference'),
        ),
        migrations.AlterField(
            model_name='genomicstudyanalysis',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='genomic_study_analysis_device', to='genomicstudies.genomicstudyanalysisdevice'),
        ),
        migrations.AlterField(
            model_name='genomicstudyanalysis',
            name='input',
            field=models.ManyToManyField(blank=True, related_name='genomic_study_analysis_input', to='genomicstudies.genomicstudyanalysisinput'),
        ),
        migrations.AlterField(
            model_name='genomicstudyanalysis',
            name='output',
            field=models.ManyToManyField(blank=True, related_name='genomic_study_analysis_output', to='genomicstudies.genomicstudyanalysisoutput'),
        ),
        migrations.AlterField(
            model_name='genomicstudyanalysis',
            name='performer',
            field=models.ManyToManyField(blank=True, related_name='genomic_study_analysis_performer', to='genomicstudies.genomicstudyanalysisperformer'),
        ),
        migrations.AlterField(
            model_name='genomicstudyanalysis',
            name='protocol_performed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='genomic_study_analysis_protocol_performed', to='genomicstudies.genomicstudyanalysisprotocolperformedreference'),
        ),
        migrations.AlterField(
            model_name='genomicstudyanalysisinput',
            name='generated_by_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='genomic_study_analysis_input_generated_by_reference', to='genomicstudies.genomicstudyreference'),
        ),
        migrations.AlterField(
            model_name='genomicstudyanalysisperformer',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='genomic_study_analysis_performer_actor', to='genomicstudies.genomicstudyanalysisperformeractorreference'),
        ),
        migrations.AlterField(
            model_name='genomicstudyreference',
            name='genomic_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='genomic_study_reference_genomic_study', to='genomicstudies.genomicstudy'),
        ),
    ]
