# Generated by Django 5.2 on 2025-04-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_initial'),
        ('episodeofcares', '0004_alter_episodeofcare_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterepisodeofcarereference',
            name='episode_of_care',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='encounter_episode_of_care_reference_episode_of_care', to='episodeofcares.episodeofcare'),
        ),
    ]
