# Generated by Django 5.2 on 2025-04-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
        ('patients', '0002_initial'),
        ('persons', '0001_initial'),
        ('practitioners', '0001_initial'),
        ('relatedpersons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communication',
            new_name='OralCommunication',
        ),
    ]
