# Generated by Django 5.2 on 2025-04-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_communication_oralcommunication'),
        ('patients', '0002_initial'),
        ('persons', '0001_initial'),
        ('practitioners', '0001_initial'),
        ('relatedpersons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OralCommunication',
            new_name='Communication',
        ),
    ]
